name: clarity
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - gettext=0.21.0=hf68c758_0
  - git-lfs=3.3.0=ha770c72_0
  - icu=58.2=hf484d3e_1000
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libxml2=2.9.14=h74e7548_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - antlr4-python3-runtime==4.8
      - bitarray==2.6.2
      - cffi==1.15.1
      - charset-normalizer==3.0.1
      - colorama==0.4.6
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.33
      - fairseq==0.12.2
      - filelock==3.9.0
      - fonttools==4.38.0
      - huggingface-hub==0.12.0
      - hydra-core==1.0.7
      - hyperpyyaml==1.1.0
      - idna==3.4
      - jiwer==2.5.1
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - levenshtein==0.20.2
      - lxml==4.9.2
      - matplotlib==3.6.3
      - numpy==1.24.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - omegaconf==2.0.6
      - packaging==23.0
      - pillow==9.4.0
      - portalocker==2.7.0
      - pycparser==2.21
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pyyaml==6.0
      - rapidfuzz==2.13.7
      - regex==2022.10.31
      - requests==2.28.2
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - sacrebleu==2.3.1
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - sentencepiece==0.1.97
      - setuptools==67.0.0
      - six==1.16.0
      - soundfile==0.11.0
      - speechbrain==0.5.13
      - tabulate==0.9.0
      - tensorboardx==2.5.1
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchinfo==1.7.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - transformers==4.28.1
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - wheel==0.38.4
prefix: /jmain02/home/J2AD003/txk68/gxc35-txk68/.conda/envs/clarity
